### ISSUE TITLE
Multiplayer and Network Support

### ISSUE THREAD

**Issue by alex-d-fox** [felicien-brochu/selflessheroes#13]
I think this needs Multiplayer and Network Support!
For Education Institutions!

**Comment by felicien-brochu** [comment]
Could you be more specific? In what way the game could become multiplayer? What do you mean by network support?

**Comment by alex-d-fox** [comment]
Multiplayer Collaborative Coding mode. - each level could either have co-op coding or per hero coding.
Networking Support for students at home and in different classrooms.

**Comment by felicien-brochu** [comment]
Introducing this kind of multiplayer aspect would mean the game would become a completely different game. The networking support would mean free cloud storage, because the game is free for students. I do not intend to add this feature. If you want your game to be saved in the cloud, you can buy the Steam version.
